name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # É uma boa prática definir um intervalo de versão

dependencies:
  flutter:
    sdk: flutter
  
  # Adicione outras dependências aqui
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 # Use a versão mais recente
  intl: ^0.20.2 # Adicione esta linha

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Use a versão mais recente

flutter:
  uses-material-design: true